In [1]:
#### 1. 대륙별 행복지수 수평막대그래프 
#### 2. 나라별 행복지수 수평막대그래프(상,하위 5개국)
#### 3. 변수들간의 상관계수 히트맵
#### 4. 각 변수별 행복지수(HS)와 상관계수 히트맵
#### 5. HS, log_gdp, life_exp의 산점도 
#### 6. HS, corruption, birth 의 산점도

In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
file_path='C:/pyy/pjt/'

In [4]:
df= pd.read_csv('C:/py/pjt/happy_0814.csv')
df.shape

(1881, 17)

In [6]:
df.columns

Index(['country', 'year', 'HS', 'log_gdp', 'social', 'life_exp', 'freedom',
       'generosity', 'corruption', 'schooling', 'alcohol', 'suicide',
       'obesity', 'birth', 'mental', 'country_num', 'continent'],
      dtype='object')

In [11]:
df[df['country']=='China']

,country,year,HS,log_gdp,social,life_exp,freedom,generosity,corruption,schooling,alcohol,suicide,obesity,birth,mental,country_num,continent
340,China,2006,4.560,8.696,0.747,66.88,0.853,-0.176,0.747,6.9,1.158490,1.758357,5.29,1.615,6.021296,156,AS
341,China,2007,4.863,8.824,0.811,67.06,0.853,-0.176,0.747,7.0,1.138653,1.696771,5.58,1.617,6.118068,156,AS
342,China,2008,4.846,8.911,0.748,67.24,0.853,-0.092,0.747,7.0,1.131244,1.610663,5.82,1.620,6.064180,156,AS
343,China,2009,4.454,8.996,0.798,67.42,0.771,-0.160,0.747,7.1,1.121180,1.565524,6.18,1.623,6.136730,156,AS
344,China,2010,4.653,9.092,0.768,67.60,0.805,-0.133,0.747,7.3,1.106153,1.506470,6.45,1.627,6.129704,156,AS
345,China,2011,5.037,9.179,0.787,67.76,0.824,-0.186,0.747,7.4,1.093972,1.426185,6.73,1.632,6.140133,156,AS
346,China,2012,5.095,9.249,0.788,67.92,0.808,-0.185,0.747,7.5,1.090947,1.367263,7.03,1.639,6.133233,156,AS
347,China,2013,5.241,9.319,0.778,68.08,0.805,-0.158,0.747,7.5,1.088449,1.335400,7.31,1.647,6.137306,156,AS
348,China,2014,5.196,9.386,0.820,68.24,0.805,-0.217,0.747,7.6,1.096560,1.303487,7.56,1.656,6.044457,156,AS
349,China,2015,5.304,9.449,0.794,68.40,0.805,-0.244,0.747,7.7,1.104623,1.264731,7.75,1.665,5.952693,156,AS
350,China,2016,5.325,9.510,0.742,68.70,0.805,-0.228,0.747,7.8,1.106245,1.231630,7.88,1.675,5.917190,156,AS
351,China,2017,5.099,9.571,0.772,69.00,0.878,-0.175,0.747,7.8,1.102624,1.230228,7.88,1.683,5.961470,156,AS
352,China,2018,5.131,9.632,0.788,69.30,0.895,-0.159,0.747,7.8,1.102624,1.230228,7.88,1.690,5.961470,156,AS
353,China,2019,5.144,9.688,0.822,69.60,0.927,-0.173,0.747,7.8,1.102624,1.230228,7.88,1.696,5.961470,156,AS
354,China,2020,5.771,9.702,0.808,69.90,0.891,-0.103,0.747,7.8,1.102624,1.230228,7.88,1.700,5.961470,156,AS

In [12]:
df[df['country']=='Chile']

,country,year,HS,log_gdp,social,life_exp,freedom,generosity,corruption,schooling,alcohol,suicide,obesity,birth,mental,country_num,continent
325,Chile,2006,6.063,9.850,0.836,68.66,0.744,0.168,0.634,9.5,3.435037,2.234209,11.56,1.901,8.570797,152,SA
326,Chile,2007,5.698,9.887,0.815,68.72,0.662,0.244,0.723,9.4,3.302734,2.258431,11.64,1.898,8.508708,152,SA
327,Chile,2008,5.789,9.911,0.804,68.78,0.640,0.084,0.741,9.9,3.200980,2.323400,11.65,1.895,8.514764,152,SA
328,Chile,2009,6.494,9.885,0.832,68.84,0.747,0.149,0.734,9.9,3.266387,2.311242,11.74,1.892,8.307926,152,SA
329,Chile,2010,6.636,9.931,0.857,68.90,0.786,0.108,0.702,9.8,3.163587,2.177493,11.77,1.884,8.251074,152,SA
330,Chile,2011,6.526,9.980,0.819,69.04,0.701,0.112,0.753,9.8,3.004627,2.115489,11.84,1.870,8.342732,152,SA
331,Chile,2012,6.599,10.023,0.855,69.18,0.734,0.195,0.782,9.9,2.966251,2.020700,11.93,1.849,8.347733,152,SA
332,Chile,2013,6.740,10.053,0.862,69.32,0.737,0.085,0.741,9.9,2.948921,1.962937,12.02,1.821,8.287403,152,SA
333,Chile,2014,6.844,10.059,0.862,69.46,0.733,0.217,0.758,10.1,2.893576,1.940993,12.07,1.787,8.279216,152,SA
334,Chile,2015,6.533,10.070,0.827,69.60,0.769,0.041,0.812,10.3,2.931755,1.907364,12.15,1.750,8.215110,152,SA
335,Chile,2016,6.579,10.074,0.841,69.70,0.652,0.102,0.858,10.3,2.991832,1.885013,12.24,1.713,8.183092,152,SA
336,Chile,2017,6.320,10.072,0.880,69.80,0.790,-0.020,0.836,10.3,3.032239,1.834583,12.33,1.678,8.106312,152,SA
337,Chile,2018,6.436,10.097,0.890,69.90,0.789,-0.060,0.816,10.3,3.032239,1.834583,12.33,1.649,8.106312,152,SA
338,Chile,2019,5.942,10.095,0.869,70.00,0.659,-0.103,0.860,10.3,3.032239,1.834583,12.33,1.627,8.106312,152,SA
339,Chile,2020,6.151,10.020,0.888,70.10,0.781,0.033,0.812,10.3,3.032239,1.834583,12.33,1.611,8.106312,152,SA